INCLUDE "hardware.inc"

SECTION "VBlankStage", ROM0[$40]
VBlankStage:
    call VBlankHandler
    reti

SECTION "VBlankIntHandler", ROM0
VBlankHandler:
    reti

SECTION "STATStage", ROM0[$48]
STATHandler:
    reti

SECTION "STATIntHandler", ROM0
STATHandler:
    reti

SECTION "TimerStage", ROM0[$50]
TimerHandler:
    reti

SECTION "SerialStage", ROM0[$58]
SerialHandler:
    reti

SECTION "JoypadStage", ROM0[$60]
JoypadHandler:
    reti