INCLUDE "hardware.inc"

SECTION "Video Utils", ROM0

HBlankWait::
    ;TODO: implement
    ret

VBlankWait::
    ;143 - 144 = -1 (sets c flag, not z flag)
    ;144 - 144 = 0 (sets z flag, not c flag)
    ;145 - 144 = 1 (sets no flags)
    ;therefore, we can just check if the carry flag is set, if it is, we loop
    ldh a, [rLY]
    cp a, LY_VBLANK + 1 
    jr c, VBlankWait
    ret

LCDOff::
    call VBlankWait
    ld a, LCDC_OFF
    ldh [rLCDC], a
    ret